// // <copyright file="SettingsData.cs" company="PublicDomain.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:Urlister.UrlisterSettings"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public bool AlwaysOnTop { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> start on login.
        /// </summary>
        /// <value><c>true</c> if start on login; otherwise, <c>false</c>.</value>
        public bool StartOnLogin { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> start minimized.
        /// </summary>
        /// <value><c>true</c> if start minimized; otherwise, <c>false</c>.</value>
        public bool StartMinimized { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> hide in tray.
        /// </summary>
        /// <value><c>true</c> if hide in tray; otherwise, <c>false</c>.</value>
        public bool HideInTray { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:Urlister.UrlisterSettings"/> enable hotkeys.
        /// </summary>
        /// <value><c>true</c> if enable hotkeys; otherwise, <c>false</c>.</value>
        public bool EnableHotkeys { get; set; } = true;
    }
}